services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_BOOTSTRAP_ADMIN_CLIENT_ID=showdown
      - KC_BOOTSTRAP_ADMIN_CLIENT_SECRET=showdown
    ports:
      - "8080:8080"
    volumes:
      - ./realm.json:/opt/keycloak/data/import/realm.json
    command: ["start-dev", "--import-realm"]