// Generated by Wrangler by running `wrangler types --x-include-runtime`

interface Env {
	AUTHORIZATION_TOKEN_ISSUER: "http://localhost:8080/realms/Showdown";
	AUTHORIZATION_TOKEN_AUDIENCE: "account";
	AUTHORIZATION_TOKEN_JWK: string;
}
