main = "src/index.ts"

workers_dev = false

compatibility_date = "2024-10-11"
compatibility_flags = ["nodejs_compat"]

[vars]
AUTHORIZATION_TOKEN_JWK="placeholder"
AUTHORIZATION_TOKEN_ISSUER="http://localhost:8080/realms/Showdown"
AUTHORIZATION_TOKEN_AUDIENCE="showdown"

[env.beta]
name = "bastion-beta"
route = { pattern = "api-beta.showdown.dev", custom_domain = true }

[env.prod]
name = "bastion"
route = { pattern = "api.showdown.dev", custom_domain = true }