main = "src/index.ts"

workers_dev = false

compatibility_date = "2024-10-11"
compatibility_flags = ["nodejs_compat"]

[env.beta]
name = "bastion-beta"
route = { pattern = "api.beta.showdown.dev", custom_domain = true }

[env.prod]
name = "bastion"
route = { pattern = "api.showdown.dev", custom_domain = true }